#+title: Index
#+bibliography: /home/alex/stack/bib/cyber_security.bib
#+cite_export: basic author-year author

* Background
=ffuf= *Fuzz Faster U Fool* written in =Go=.


* Introduction
Fuzzing is the process or technique of sending a number of request to as target site in a certain interval of time. In other words, it is also similar to bruteforcing. Fuzzing is a process which can be achieved using tools like Wfuzz, ffuf, and so on. As a tester you would need to provide the tool with the target URL, parameter, endpoint, etc, and some sort of inputs. Then the fuzzing tool crafts requests and sends them to the target. After the fuzzing has finished, the responses, timing, status codes, and other characteristics need to be analyzed for potential vulnerabilities.


* intall
#+begin_src bash
cd \
sudo apt update && sudo apt install golang-go \
git clone https://github.com/ffuf/ffuf && cd ffuf && go get && go build \
mv ffuf ../.local/bin/


#+end_src

#+RESULTS:

* Examples

** subdomain

For fuzzing a =subdomain= we encouter sometimes a subdomain and add this to our hosts file.

#+begin_src bash
ffuf -w /usr/share/wordlists/seclists/Discovery/DNS/combined_subdomains.txt -u http://$URL/ -H 'Host: FUZZ.$URL' -mc

#+end_src

** pages

#+begin_src bash
ffuf -w /usr/share/wordlists/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt:FUFF -u http://$URL/FUFF -ic -t 100
#+end_src

- =-w= =wordlist=,
- =-u= target =URL=,
- =-ic= ignores wordlist comments,
- =-t 100= Specifies threads for concurrent requests  
